### ISSUE TITLE
allow including results from forks

### ISSUE THREAD

**Issue by maxandersen** [hub4j/github-api#1154]
**Describe the bug**
searchContent() does not seem to have a flag/method to enable searching content in forks, i.e. what corresponds to choosing "Fork" in the "Filters" section when searching, i.e.:

https://github.com/search?q=topic%3Ajbang-appstore+fork%3Atrue&type=repositories

**Expected behavior**
Ability to have search include results in forks.

**Comment by maxandersen** [comment]
Ha. I thought that 'v' meant something else. Would have been good if the javsdocs itself stated what values was expected :)

**Comment by akashRindhe** [comment]
Agreed that the docs could be a lot better. Additionally, an `enum` specifying the acceptable values instead of a `String` would make it self explanatory.

**Comment by maxandersen** [comment]
so...just tried this now and it is not giving any additional results:

`gitHub.searchContent().fork("true")..`

also tried with "only" and still no results.

**Comment by bitwiseman** [comment]
@maxandersen  @akashRindhe 

We have one test method currently: 
https://github.com/hub4j/github-
api/blob/d0912009dd84c55190f01034a59aa3f8ec62fdf5/src/test/java/org/kohsuke/github/GitHubTest.java#L94-L155

It looks like `fork` isn't covered.  😞  Test and possible fix welcome.

**Comment by sahansera** [comment]
Hey @bitwiseman, I would like to look into this issue as well. Could you assign it to me? Thank you!

**Comment by sahansera** [comment]
I had a closer look at the issue and I believe we are talking about 2 facets in here - i.e. Repository search and Code search. 

1. **Repository search** `(type=Repositories)`
I was able to figure out a way to handle the use case explained by @maxandersen by using the `searchRepositories()` method.

```java
var repos = github.searchRepositories()
        .q("jbang-appstore")
        .fork(GHRepositorySearchBuilder.Fork.PARENT_AND_FORKS)
        .order(GHDirection.DESC)
        .list();
repos.toList().forEach(ghRepository -> System.out.println(ghRepository.getFullName() + " " + ghRepository.isFork()));
```

This will output the following:

```
maxandersen/jbang-catalog false
gunnarmorling/jbang-catalog true
```
which matches with

2. **Code search** `(type=Code)`
GitHub doesn't index the content of forks if they don't have more stars than the parent repo. To quote the API [docs](https://docs.github.com/en/search-github/searching-on-github/searching-code#considerations-for-code-search):

> Code in forks is only searchable if the fork has more stars than the parent repository. Forks with fewer stars than the parent repository are not indexed for code search.

This is why we don't get any results if we do a code search like this. I am happy to look at any sample use cases you might have that returns valid results.

However, I agree with what has been discussed here about refactoring the code to be able to use an enum for the `searchContent().fork("")` instead of passing strings which makes the code more self-explanatory. I am happy to do that change as part of this issue if you think that's beneficial.

Let me know what you think about this @bitwiseman 

Cheers :)

**Comment by sahansera** [comment]
Based on the above comment I have created a draft PR to know your thoughts. I can target the `hub4j` repo if you are happy with it. PR - https://github.com/sahansera/github-api/pull/1

**Comment by bitwiseman** [comment]
@sahansera 
Thanks for the PR. The change looks basically good. I've commented.

**Comment by sahansera** [comment]
@bitwiseman Thanks a lot for reviewing, improving and merging this PR. I really like the new `GHQueryBuilder` 🎉 It's been a great learning opportunity!

Are we able to close this issue as well?
