### ISSUE TITLE
GHCompare - support parameters "per_page" and "page"

### ISSUE THREAD

**Issue by ravingbool** [hub4j/github-api#1209]
Hello, does it in the roadmaps to support those parameters?
Github changed the Compare two Commits API, so now it is possible to get over 250 commits:
https://github.blog/changelog/2021-03-22-compare-rest-api-now-supports-pagination/

Best regards, Max

**Comment by bitwiseman** [comment]
For reference: https://docs.github.com/en/rest/reference/repos#compare-two-commits says 

> To process a response with a large number of commits, you can use (per_page or page) to paginate the results. When using paging, the list of changed files is only returned with page 1, but includes all changed files for the entire comparison.

> When calling this API without any paging parameters (per_page or page), the returned list is limited to 250 commits and the last commit in the list is the most recent of the entire comparison. When a paging parameter is specified, the first commit in the returned list of each page is the earliest.

This means that https://api.github.com/repos/hub4j/github-api/compare/github-api-1.100...github-api-1.131?per_page=5&page=1 looks like: 

```json
{
  "url": "https://api.github.com/repos/hub4j/github-api/compare/github-api-1.100...github-api-1.131",
  "html_url": "https://github.com/hub4j/github-api/compare/github-api-1.100...github-api-1.131",
  "permalink_url": "https://github.com/hub4j/github-api/compare/hub4j:f7d048e...hub4j:94ff089",
  "diff_url": "https://github.com/hub4j/github-api/compare/github-api-1.100...github-api-1.131.diff",
  "patch_url": "https://github.com/hub4j/github-api/compare/github-api-1.100...github-api-1.131.patch",
  "base_commit": { ... },
  "merge_base_commit": { ... },
  "status": "ahead",
  "ahead_by": 1339,
  "behind_by": 0,
  "total_commits": 1339,
  "commits": [ <5 commits for page 1> ]
  "files": [ <all changed files for all commits from all pages>  ]
}
```

And https://api.github.com/repos/hub4j/github-api/compare/github-api-1.100...github-api-1.131?per_page=5&page=2 looks like: 

```json
{
  "url": "https://api.github.com/repos/hub4j/github-api/compare/github-api-1.100...github-api-1.131",
  "html_url": "https://github.com/hub4j/github-api/compare/github-api-1.100...github-api-1.131",
  "permalink_url": "https://github.com/hub4j/github-api/compare/hub4j:f7d048e...hub4j:94ff089",
  "diff_url": "https://github.com/hub4j/github-api/compare/github-api-1.100...github-api-1.131.diff",
  "patch_url": "https://github.com/hub4j/github-api/compare/github-api-1.100...github-api-1.131.patch",
  "base_commit": { ... },
  "merge_base_commit": { ... },
  "status": "ahead",
  "ahead_by": 1339,
  "behind_by": 0,
  "total_commits": 1339,
  "commits": [ <5 commits for page 2> ]
}
```

This is a very odd behavior.  

All the other endpoints that support `per_page` and `page` parameters use `PagedIterable` to iterate over items.  However, those endpoints also for the most part return simple lists.  There are also some endpoints that return pages as relatively sparse objects that then contain lists. 

For example `GHRepository.getCheckRuns` returns `PagedIterable<GHCheckRun>`:

https://github.com/hub4j/github-api/blob/4247c8a60d809994836d67fe6ce3ad4d5d115406/src/main/java/org/kohsuke/github/GHRepository.java#L2027-L2033

This actually an instance of [GHCheckRunsIterable](https://github.com/hub4j/github-api/blob/4247c8a60d809994836d67fe6ce3ad4d5d115406/src/main/java/org/kohsuke/github/GHCheckRunsIterable.java#L10) which pages through [GHCheckRunsPage](https://github.com/hub4j/github-api/blob/4247c8a60d809994836d67fe6ce3ad4d5d115406/src/main/java/org/kohsuke/github/GHCheckRunsPage.java#L6) objects.

I think the right way to address this will be to add `GHCompare.listCommits()` method that returns a `PagedIterable<Commit>` and internally implements something like `GHCheckRunsIterable` that uses `GHCompare` objects as the pages. Then add a method `GHRepository.getCompare(String id1, String id2, int default_commits_per_page)`.  The query for that would set `per_page` to 1 and set a new field in `GHCompare` to the `default_commits_per_page`.  If that field is set, `GHCompare.listCommits()` would have it's `per_page` set to the that by default and `GHCompare.getCommits()` would call `listCommits().getArray()` instead of it's current behavior.
