### ISSUE TITLE
404 error in javadoc when try to search

### ISSUE THREAD

**Issue by worldbiomusic** [hub4j/github-api#1402]
**Describe the bug**
404 error in Java doc when try to search.

**To Reproduce**
1. Go to [javadoc](https://github-api.kohsuke.org/apidocs/index.html)
2. Search `GHRepository`
3. See error

**Expected behavior**
- It looks javadoc needs to be regenerated

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: latest

**Additional context**
- Good project, thank you!.

**Comment by 0xacx** [comment]
When manually navigating to the file, the path is correct and you can view the file. `https://github-api.kohsuke.org/apidocs/org/kohsuke/github/GHRepository.html`
When searching for the file, `undefined` is added to the path,  for classes that don't belong in modules,
`https://github-api.kohsuke.org/apidocs/undefined/org/kohsuke/github/GHRepository.html`, thus making the request return 404.

There are a few workarounds discussed in [SO](https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url) but probably the cleanest solution is generating the javadoc with a version higher than 11 where this bug is fixed.

**Comment by bitwiseman** [comment]
@0xacx  @worldbiomusic 
It looks like #1434 fails due to more stringent doclint behavior in Java 17.  Would either of you be willing to do the work to address the new warnings?

**Comment by arslanakhtar61** [comment]
The j[javadoc](https://github-api.kohsuke.org/apidocs/index.html) url is unavailable!
