### ISSUE TITLE
Does withPageSize api work?

### ISSUE THREAD

**Issue by appkr** [hub4j/github-api#1419]
Thanks for providing such a nice library.

As the title says, I am having trouble using `withPageSize(int)` api.
```java
private Mono<SortedSet<Event>> getEvents(GHRepository repository) {
  SortedSet<Event> events = new TreeSet<>();
  try {
    // It seems that withPageSize(int) does not work
    final PagedIterator<GHEventInfo> iterator = repository.listEvents().iterator();
    // ...
```

Not support paging for GHEventInfo is BY DESIGN?
OR did I make a silly mistake in using the api?

Look forward to have an help. Thanks.

**Comment by appkr** [comment]
ADDITIONAL NOTE: I expected `withPageSize(10)` yields only 10 items, but 300.
<img width="902" alt="스크린샷 2022-04-03 오전 9 28 12" src="https://user-images.githubusercontent.com/6471947/161406105-83e951f4-c250-4152-8bfe-fb94129d32fd.png">

**Comment by bitwiseman** [comment]
https://docs.github.com/en/rest/reference/activity#list-repository-events says that the `/repos/{owner}/{repo_name}/events` endpoint supports `per_page`... Oh, wait, I see the problem. 

The `PagedIterator<>.toList()` method always returns the complete list of all results. [This is by design.](https://github.com/hub4j/github-api/blob/9e440f59ed40a60fe27264e0f79e4c3be1e4252c/src/main/java/org/kohsuke/github/PagedIterable.java#L109-L115)  

What you want seems to be: 
```
final PagedIterator<GHEventInfo> iterator = repository.listEvents().withPageSize(10).iterator();
List<GHEventInfo> ghEventInfos = iterator.nextPage();
```

As noted https://github.com/hub4j/github-api/issues/348#issuecomment-887050145 , it would be clear to add a method called `pageIterator()` that returns an iterator of `List<T>`.

**Comment by appkr** [comment]
Thanks for the kind answer. The usage example works correctly.
