### ISSUE TITLE
org.kohsuke.github.HttpException while updating file content

### ISSUE THREAD

**Issue by nikhilkr123** [hub4j/github-api#658]
**Description**
I am getting following error while updating a file content if file is updated externally after creating `GitHub` object.

> org.kohsuke.github.HttpException: {"message":"is at 00af843ca70ac16c2f17eb12ff18b220b807a791 but expected cb3152336469683a61509e2e311268c8933bd128","documentation_url":"https://developer.github.com/v3/repos/contents/#create-or-update-a-file"}
at org.kohsuke.github.Requester.handleApiError(Requester.java:903)
at org.kohsuke.github.Requester._to(Requester.java:415)
at org.kohsuke.github.Requester.to(Requester.java:353)
at org.kohsuke.github.GHContent.update(GHContent.java:319)
at org.kohsuke.github.GHContent.update(GHContent.java:256)

**Steps**
1. Create a file in Git
2. Create an instance of `GitHub` and `GHRepository`
3. Update the file using `repo.getFileContent("myfile.txt").update("file body", commitMsg);`
4. Update the file few times manually using Git (i.e few commits)
5. Repeat step 3

I think we need to rebase the repo before updating the file. But how do I do it using this SDK ?

**Comment by bitwiseman** [comment]
What version of the library are you using?

**Comment by nikhilkr123** [comment]
1.101

**Comment by bitwiseman** [comment]
I'm still a little unclear on the exact steps.  

For step 5 do you do `repo.getFileContent("myfile.txt").update("file body", commitMsg);` or are you doing something that you believe to be equivalent?  

What happens if for step 5 you do steps 2 and 3 (instead of just 3)?  
What happens if you do step 5 on another client?   (For instance, if you alternate step 3 on two different clients.)

This sounds like a caching or out of sync issue of some kind but it might be on the github api side or it might be on the client side.  I don't think rebasing is what's needed but I could be missing some detail.

**Comment by nikhilkr123** [comment]
1. I am doing `repo.getFileContent("myfile.txt").update("file body", commitMsg)` , nothing else
2. I tried step 2 & 3 as part of step 5, but same results.

**Comment by nikhilkr123** [comment]
1. I am doing `repo.getFileContent("myfile.txt").update("file body", commitMsg)` , nothing else
2. I tried step 2 & 3 as part of step 5, but same results.

**Comment by bitwiseman** [comment]
@nikhilkr123 
Can you write a test in this repo the reproduces this.  If you can, you can record it using the process described in the CONTRIBUTING.md. That would go a long way to getting this addressed.

**Comment by bitwiseman** [comment]
Closing for now.  Happy to reopen if new information is provided.
