### ISSUE TITLE
NullPointerException when retrieve a review's user if it's deleted

### ISSUE THREAD

**Issue by ghost** [hub4j/github-api#771]
**Describe the bug**
[This line](https://github.com/github-api/github-api/blob/master/src/main/java/org/kohsuke/github/GHPullRequestReview.java#L81) throws an NPE if the reviewer's user account is deleted in github

**To Reproduce**
1. Create a Pull Request in a Github repo
2. Register a new github user
3. Use the new user to add a review (e.g. comment + approval) of the pull request
4. Delete that new github user account
5. Try use this API to fetch the review user (i.e. call `review.getUser();` on that `GHPullRequestReview` object.
6. There would an uncaught NullPointerException.

**Expected behavior**
Perhaps returns a null user?

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: N/A
 - Version: 1.1.06

**Additional context**

**Comment by sahansera** [comment]
Hi @bitwiseman I had a look into this issue and found that this might not be the case anymore. However, I investigated a bit further and I observed the following behaviours during my initial tests.

1. `User A` requests a PR review from a `User B`. `User B` gets deleted. GitHub removes the requested reviewer from the PR. 
    - If we do a `pr.getRequestedReviewers()` on the PR the list that gets returned will be empty.
    - Sample PR can be found [here](https://github.com/sahansera/TestRepo/pull/1)
    
```java
GitHub github = new GitHubBuilder().withOAuthToken("PAT").build();
var repo = github.getRepository("sahansera/TestRepo");
var pr = repo.getPullRequest(2);
var reviewer = pr.getRequestedReviewers();
```

2. `User A` requests a PR review from a `User B`. `User A` gets deleted. GitHub assigns a [ghost](https://github.com/ghost) account to `User A`. 
     - If we do a `pr.getUser()` it returns the details of the `ghost` user account. But it will not be null
     - Sample PR can be found [here](https://github.com/sahansera/TestRepo/pull/2)

```java
GitHub github = new GitHubBuilder().withOAuthToken("PAT").build();
var repo = github.getRepository("sahansera/TestRepo");
var pr = repo.getPullRequest(2);
var reviewer = pr.getUser();
```

- Would you mind if I assign this task to myself?
- Do you think it's a good idea to add some unit tests around this to validate it? I am happy to work on any test cases cover these scenarios.

Thank you!

**Comment by sahansera** [comment]
@bitwiseman 

Thanks again for assigning me this task and adding me to the test org.

I initially went down the path trying to create a PR then assign/remove reviewers. However, it's going to be tricky since we can't assign a non-existing user to a PR programmatically. What I would suggest is, we create two PRs in the `hub4j-test-org` to simulate the above two scenarios and use their Ids in the unit tests and perform the assertions.

If this sounds like a good plan, would you be able to create two PRs in `hub4j-test-org` for me (since I don't have admin rights I can't assign people to PRs).

1. PR 1 - Author gets deleted.
2. PR 2 - Reviewer gets deleted. Additionally, we could add a comment from the reviewer too.

I have two unit tests targeting my sample [repo](https://github.com/sahansera/TestRepo/pulls?q=is%3Apr+is%3Aclosed) that are ready to go. I can perform a snapshot and update my changes and raise a PR.

**Comment by bitwiseman** [comment]
You might have to write custom wiremock stubs, or record different stubs and then mix and match them to get the set of responses that will exercise this scenario.

**Comment by sahansera** [comment]
@bitwiseman No problem! Thanks a lot for the suggestion. I have followed your approach and created a PR [here](https://github.com/hub4j/github-api/pull/1318).

In summary, I first ran the WireMock snapshots for my test repo and edited them manually so that they cover all the scenarios and comply with the `getRepository()` method.
