### ISSUE TITLE
ghreaction deprecated, any alternative ? 

### ISSUE THREAD

**Issue by maxandersen** [hub4j/github-api#815]
**Describe the bug**
I noticed ghReaction and all the apis around it are deprecated.

it is also superslow to use - I reckon that could be part of the deprecation :)

Question is if there is an alternative since its marked deprecated ?

**Comment by bitwiseman** [comment]
Preview APIs are marked as deprecated in order to warn consumers of this library that they may change without warning (due to GitHub API itself changing). 

GHReaction is in preview.  

https://github.com/hub4j/github-api/blob/a42305dd59f0be426f0c9091748e947f60d76bcd/src/main/java/org/kohsuke/github/GHReaction.java#L14-L16
