### ISSUE TITLE
Failing to get sha for bigger files

### ISSUE THREAD

**Issue by Osiris-Team** [hub4j/github-api#878]
**Im trying to get the sha by using following code:**

```java
String sha = repo.getFileContent("my/file.txt").getSha();
```

**But I get this error:**
org.kohsuke.github.HttpException: {"message":"This API returns blobs up to 1 MB in size. The requested blob is too large to fetch via the API, but you can use the Git Data API to request blobs up to 100 MB in size.","errors":[{"resource":"Blob","field":"data","code":"too_large"}],"documentation_url":"https://developer.github.com/v3/repos/contents/#get-contents"}

**Is there a possibility to switch to Git Data or is there another workaround for this?**

**Comment by bitwiseman** [comment]
# Summary
Using Git Data is a bit more involved.  The current design in this library is not very friendly.  This is partly due to the REST API not being very friendly but also due to it not being as heavily used.  

# Current way to use Git Data 

```
String sha;
GHCommit commit = repo.getCommit("master");
GHTreeEntry entry = commit.getTree().getEntry("my/file.txt");
if (entry != null) {
    sha = entry.getSha();
    // To get the contents (if that is what you plan to do next) 
    GHBlob blob = entry.asBlob();
    String contents = blob.getContent();
}   
```

**Comment by bitwiseman** [comment]
The rest of this 

# Possible improvements to this library

I was about to say that the roughness of the above code was due to the Server-side REST API not supporting getting paths directly.  The [documentation for trees]( https://developer.github.com/v3/git/trees/) says that you can only pass `tree_sha`. 

Let's look at how we'd get the blob for `src/main/java/org/kohsuke/github/GHApp.java` at the tag `github-api-1.100`.

## Blob from Tree (version 1)

1. Request https://api.github.com/repos/hub4j/github-api/commits/github-api-1.100 
2. Get the `tree.sha`: `9bb863419bea20c2b43bb062a9a6fac4d51a070f`
3. Request https://api.github.com/repos/hub4j/github-api/git/trees/9bb863419bea20c2b43bb062a9a6fac4d51a070f
4. Traverse the layers of tree entries to get to `src/main/java/org/kohsuke/github` (multiple REST API calls)
5. Get the blob for `GHApp.java`: https://api.github.com/repos/hub4j/github-api/git/blobs/affdf9eca16bdff21a8a21a5386dbe4aa7cfed26

## General improvements
* In most cases, we can add `?recursive=true` to step 3. Then step 4 becomes a single API call and a search through the list of all entries. 
* `tree_sha` can be changed to the commit for `github-api-1.100` itself: `https://api.github.com/repos/hub4j/github-api/git/trees/f7d048e0b9a3748b6d75f2871c8471be7c29148e`.
** (even better)`tree_sha` can be changed to tag name: https://api.github.com/repos/hub4j/github-api/git/trees/github-api-1.100`

## Blob from Tree (version 2)

1. Request https://api.github.com/repos/hub4j/github-api/git/trees/github-api-1.100?recursive=true
2. Search list of tree entries to get to `src/main/java/org/kohsuke/github/GHApp.java`
3. Get the blob for `GHApp.java`: https://api.github.com/repos/hub4j/github-api/git/blobs/affdf9eca16bdff21a8a21a5386dbe4aa7cfed26

## Use "extended SHA-1" for Tree 

The `tree_sha` improvements we made above indicate that the github docs, while accurate do not communicate the power and flexibility of the Git Data API.  

I found [this SO article](https://stackoverflow.com/questions/26203603/how-do-i-get-the-sha-parameter-from-github-api-without-downloading-the-whole-f) that shows how to use  "[extended SHA-1 syntax](https://git-scm.com/docs/gitrevisions)" to get a [specific tree path](https://git-scm.com/docs/gitrevisions#Documentation/gitrevisions.txt-emltngtltpathgtemegem0READMEememREADMEem). 

This means steps 1 can be shortened to get the specific directory we want rather than the recursive tree entry list for the whole repo: `https://api.github.com/repos/hub4j/github-api/git/trees/github-api-1.100%3Asrc%2Fmain%2Fjava%2Forg%2Fkohsuke%2Fgithub`.  

## Use "extended SHA-1" for Blob? 

Just as the Tree API has `tree_sha`, the Blob API has `blob_sha`. They're both SHAs... maybe could use extended SHA-1 syntax for blobs as well?  

```
https://api.github.com/repos/hub4j/github-api/git/blobs/github-api-1.100%3Asrc%2Fmain%2Fjava%2Forg%2Fkohsuke%2Fgithub%2FGHApp.java

{
  "message": "The sha parameter must be exactly 40 characters and contain only [0-9a-f].",
  "documentation_url": "https://developer.github.com/v3/git/blobs/#get-a-blob"
}

Nope. 

## Blob from Tree (version 3)

1. Request tree for `github-api-1.100:src/main/java/org/kohsuke/github`: https://api.github.com/repos/hub4j/github-api/git/trees/github-api-1.100%3Asrc%2Fmain%2Fjava%2Forg%2Fkohsuke%2Fgithub
2. Search list of tree entries in `src/main/java/org/kohsuke/github` to get to `src/main/java/org/kohsuke/github/GHApp.java`
3. Get the blob for `GHApp.java`: https://api.github.com/repos/hub4j/github-api/git/blobs/affdf9eca16bdff21a8a21a5386dbe4aa7cfed26


Trees: https://developer.github.com/v3/git/trees/
The git data api Blobs docs: https://developer.github.com/v3/git/blobs/

**Comment by Osiris-Team** [comment]
@bitwiseman Wow! Great work and thanks for the help 💙

**Comment by Osiris-Team** [comment]
> # Summary
> Using Git Data is a bit more involved. The current design in this library is not very friendly. This is partly due to the REST API not being very friendly but also due to it not being as heavily used.
> 
> # Current way to use Git Data
> ```
> String sha;
> GHCommit commit = repo.getCommit("master");
> GHTreeEntry entry = commit.getTree().getEntry("my/file.txt");
> if (entry != null) {
>     sha = entry.getSha();
>     // To get the contents (if that is what you plan to do next) 
>     GHBlob blob = entry.asBlob();
>     String contents = blob.getContent();
> }   
> ```

@bitwiseman Ok that sadly didnt work but I found another workaround.
I deleted the old file wich I was trying to update. This is the code. Please updload it to your documentation cause it took me hours to figure out and other newbies also will fuck their head with it.
```java

public static void main(String[] args) {
            //Login with AuthToken
            GitHub github = new GitHubBuilder()
                    .withOAuthToken("YOUR TOKEN HERE")
                    .build();
            System.out.println(" ");
            System.out.println(" > API-INFO >");
            System.out.println(" > Url: " + github.getApiUrl());
            System.out.println(" ");

            //Get repository
            GHRepository repo = github.getRepository("Osiris-Team/AutoPlug-Releases");

            System.out.println(" ");
            System.out.println(" > REPO-INFO >");
            System.out.println(" > Name: " + repo.getFullName());
            System.out.println(" > Stars: " + repo.getStargazersCount());
            System.out.println(" > Subs: " + repo.getSubscribersCount());
            System.out.println(" > Views: " + repo.getViewTraffic().getViews().size());
            System.out.println(" > Size: " + repo.getSize());
            System.out.println(" > Last push: " + repo.getPushedAt());
            System.out.println(" > Open issues: {[" + repo.getIssues(GHIssueState.OPEN).size() + "]}");
            System.out.println(" ");

            //Delete folder before uploading
            try {
                List<GHContent> dir_content = repo.getDirectoryContent("" + build_mode);
                for (GHContent single_content :
                        dir_content) {
                    single_content.delete("Deleted file because of update!");
                    single_content.refresh();
                }
            } catch (Exception e) {
                System.out.println(" - Failed to delete old files! No files found to delete!");
            }

            //We use the same repo but in a new object because the deleted old files interfeer
            github = new GitHubBuilder()
                    .withOAuthToken("YOUR TOKEN HERE")
                    .build();
            GHRepository repo2 = github.getRepository("Osiris-Team/AutoPlug-Releases");

            //Perform updates
            uploadFile(build_mode, tmp_autoplug, repo2);
            uploadFile(build_mode, tmp_autoplug_update_xml, repo2);

            uploadFile(build_mode, tmp_autoplugplugin, repo2);
            uploadFile(build_mode, tmp_autoplugplugin_update_xml, repo2);

            uploadFile(build_mode, tmp_autopluglauncher, repo2);
            uploadFile(build_mode, tmp_autopluglauncher_update_xml, repo2);

        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("Failed to upload files!");
        }
    }


    private static void uploadFile(String github_dir_name, File file, GHRepository repo) throws IOException {

        System.out.println("#########################################");
        System.out.println(" - Uploading to repo: " + repo.getFullName());
        System.out.println(" - File output path: " + github_dir_name+"/"+file.getName());

        //Create content
        GHContentBuilder content = repo.createContent()
        .message("Updated to latest build")
        .path(github_dir_name+"/"+file.getName()) 
        .branch("master")
        .content(Files.readAllBytes(file.toPath()));

        try {
            System.out.println(" - Uploading...");
            GHCommit commit = content.commit().getCommit();
            System.out.println(" - Upload successful at: " + commit.getCommitDate());
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println(" - Upload failed!");
        }

    }

```

**Comment by bitwiseman** [comment]
@Osiris-Team 
Yeah, that looks like a lot of work. Could you take a minute to explain what your actual goal is?  Is it just to update a set of files or is it something else?  I'm glad what you've done works but it doesn't make a lot of sense to me - it doesn't seems like something people want to do generally in git. 


Side note: 
The `refresh()` isn't needed and it results in an additional API call, using more of your rate limit.  

> ```java
> for (GHContent single_content :
>                         dir_content) {
>                     single_content.delete("Deleted file because of update!");
>                     single_content.refresh();
>                 }
> ```

**Comment by bitwiseman** [comment]
@Osiris-Team  
If you're trying to update files in a folder, I think you'll want to use [GHTreeBuilder](https://github.com/hub4j/github-api/blob/master/src/main/java/org/kohsuke/github/GHTreeBuilder.java).  The [GHTreeBuilderTest](https://github.com/hub4j/github-api/blob/master/src/test/java/org/kohsuke/github/GHTreeBuilderTest.java) shows some examples of usage. Note, when building trees if you know the files are text, you should use the String `add()` method as it will consume fewer REST API calls.  Binary files, by contast have to have blobs created and attached to the tree (done by the library). 

```java

public static void main(String[] args) {
    try {
        String build_mode = args[0];
        //Login with AuthToken
        GitHub github = new GitHubBuilder()
                .withOAuthToken("YOUR TOKEN HERE")
                .build();

        //Get repository
        GHRepository repo = github.getRepository("Osiris-Team/AutoPlug-Releases");

        GHRef masterRef repo.getRef("heads/master");
        GHCommit commit = masterRef.getCommit(masterRef.getObject().getSha());
        GHTree tree = commit.getTree();

        // Build a new tree
        GHTreeBuilder builder = repo.createTree();
        builder.baseTree(tree.getSha());
 
        //Perform updates
        // detecting if a file is text is a pain
        // https://stackoverflow.com/questions/620993/determining-binary-text-file-type-in-java

        uploadFile(builder, build_mode, tmp_autoplug, true, true);
        uploadFile(builder, build_mode, tmp_autoplug_update_xml, false, false);

        uploadFile(builder, build_mode, tmp_autoplugplugin, true, true);
        uploadFile(builder, build_mode, tmp_autoplugplugin_update_xml, false, false);

        uploadFile(builder, build_mode, tmp_autopluglauncher, true, true);
        uploadFile(builder, build_mode, tmp_autopluglauncher_update_xml, false, false);

        // Create the tree
        String treeSha = builder.create().getSha();

        // Create a commit from the tree 
        String commitSha = new GHCommitBuilder(repo).message("Updated to latest build")
                .tree(treeSha)
                .parent(masterRef.getObject().getSha())
                .create()
                .getSHA1();

        // Update master to the new commit
        masterRef.updateTo(commitSha);

    } catch (IOException e) {
        e.printStackTrace();
        System.out.println("Failed to upload files!");
    }
}


private static void uploadFile(GHTreeBuilder tree, String github_dir_name, File file, boolean isBinary, boolean isExecutable) throws IOException {
    //Create content
    if(isBinary) {
        tree.add(github_dir_name+"/"+file.getName(), Files.readAllBytes(file.toPath()), isExecutable);
    } else {
        tree.add(github_dir_name+"/"+file.getName(), new String(Files.readAllBytes(file.toPath()), "UTF-8"), isExecutable);
    }
}

```
